name: 部署服务器端代码
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Node环境
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"

      - name: 安装依赖与构建
        run: |
          cd server
          npm ci
          npm run build

      - name: upload to file
        run: ls -la /server/node_modules
