name: 前端部署工作流
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 创建目录
        run: |
          mkdir -p file1
          mkdir -p file2
          mkdir -p dist1

      - name: 创建文件
        run: |
          echo "这是文件1的内容" > file1/file1.txt
          echo "这是文件2的内容" > file2/file2.txt

      - name: upload to file
        uses: actions/upload-artifact@v4
        with:
          name: "build-output"
          path: |
            ./file1/file1.txt
            ./file2/file2.txt

      - name: download file
        uses: actions/download-artifact@v4
        with:
          name: "build-output"
          path: "./dist1"

      - name: 服务器环境准备（含Docker优化）
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          debug: true
          script: |
            # 创建目录和备份（保持原有逻辑）
            if [ ! -d "/nest/www1" ]; then
              sudo mkdir -p /nest/www1 && sudo chown -R $USER:$USER /nest/www1 && chmod 755 /nest/www1
            fi

      - name: 传输前端文件
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "dist1/file1"
          target: "/nest/www1"
          overwrite: true
          recursive: true
